name: Cypress Test UI Automation After Office Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with mochawesome reporter
        run: npx cypress run --spec 'cypress/e2e/4-e2e-test/*.cy.js'

      - name: Debug folder structure
        run: ls -R cypress

      - name: Run Cypress tests
        run: npx cypress run

      - name: Debug report output
        run: ls -R cypress/reports

      - name: Upload Cypress Reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html

      - name: Upload videos on failure (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**

      - name: Upload screenshots on failure (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**
